### ISSUE TITLE
Tool path not found 

### ISSUE THREAD

**Issue by Cheesebaron** [krippz/cake.strongnametool#3]
For some reason the sn.exe tool path isn't found on my machine. I inspected the code, and it seems to expect that stuff is in the v7.0A folder, which I have:

![image](https://cloud.githubusercontent.com/assets/249719/24292636/7bf3366e-108e-11e7-95ea-bc284ed67b32.png)

I verified that the sn.exe file is there. However, it still fails to find it.

Would it be possible to maybe override the path using the Settings you pass to the Alias, or maybe make the Resolver a bit more robust and try alternative paths as well?

```
An error occurred when executing task 'strong-name-sign'.
Error: Cake.Core.CakeException: Failed to find sn.exe.
   at Cake.StrongNameTool.StrongNameResolver.GetPath()
   at Cake.StrongNameTool.StrongNameToolRunner.GetAlternativeToolPaths(StrongNameToolSettings settings)
   at Cake.Core.Tooling.Tool`1.GetToolPathObsolete(TSettings settings)
   at Cake.Core.Tooling.Tool`1.GetToolPath(TSettings settings)
   at Cake.Core.Tooling.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)
   at Cake.StrongNameTool.StrongNameReSignToolAliases.StrongNameReSign(ICakeContext context, IEnumerable`1 assemblies, StrongNameToolSettings settings)
   at Submission#0.<.ctor>b__17()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by Cheesebaron** [comment]
Seems like: `NETFX 4.0 Tools` is not in the `Microsoft SDKs/Windows/v7.0A/Bin` folder as the Resolver expects.

**Comment by Cheesebaron** [comment]
Looking at a couple of other machines, they do not have the NETFX 4.0 Tools folder either.

**Comment by krippz** [comment]
Good catch :)
